title: Stock Management App
description: A lightweight inventory management system
baseurl: "/stock-management"
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Avoid Jekyll processing issues
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

sass:
  style: compressed